- src/app/login/page.jsx
> Pre production

- app/ingresar/page.jsx
- app/registrarse/page.jsx
cambio nombre carpetas/rutas y links.
> cambioscarpetas

- app/Components/Navbar.jsx
- Se agrego un Link al logo del NavBar
> Agregando link al icono del nav

- pages/ingresar/index.js
- pages/registrarse/index.js
> typo rutas

- pages/index.js
> typo en home

- pages/crearong/index.js
- pages/iniciativas/[id].js
> typo de importacion de paypal en id y navbar en crearong

- pages/creariniciativas/index.js
Hice que cuando se le da " enviar " en crear iniciativas, te redirija a iniciativas
> Creariniciativas

- Components/Footer.jsx
- Components/Navbar.jsx
- package-lock.json
- package.json
- pages/faq/index.js
- pages/index.js
- pages/ingresar/index.js
- pages/iniciativas/index.js
- pages/registrarse/index.js
- pages/registrarse2/index.js
- tailwind.config.js
- Nuevo estilo en el home
- Nuevo estilo en el login
- Validacion y pasos separados en el register (falta terminar)
- Nuevo estilo en iniciativas (falta terminar)
- Nueva seccion FAQ
- Nuevos estilos Navbar
- Nuevos estilos Footer
- Responsive TODA la pagina
> Nuevos estilos

- pages/crearong/index.js
> crearongfix

- Components/Formempresas.jsx
- Components/Formusers.jsx
forms para users y empresas nuevos
> formsusersyempresas

- Components/Card.jsx
- pages/registrarse/index.js
- Agregando tercer step de registor de usuarios y empresas
- Renderizado de imagenes en Cards (Estaban hard codeadas)
> Estilos bauti

- Components/Formempresas.jsx
- Components/Formusers.jsx
- Components/Navbar.jsx
- Components/createONG.jsx
- pages/creariniciativas/index.js
- pages/ingresar/index.js
- pages/perfil/index.js
- pages/registrarse/index.js
falta probar el login de Ingresar y q cuando vuelvas desp de deslogearte se renderize de nuevo la navbar. etc
> Loginlocal

- pages/ingresar/index.js
hardcodeo del login type_of_user
> hardcodeo del login type_of_user

- .env
- Components/Formusers.jsx
- Components/UserNavbar.jsx
- Components/createONG.jsx
- Components/emailPost.js
- hooks/user.js
- pages/creariniciativas/index.js
- pages/ingresar/index.js
- pages/review/index.js
falta q ande el post al back y estilos
> Formreview

- pages/iniciativas/index.js
Está funcionando pero por algun motivo no me anda el renderizado
> Falta arreglar renderizado

- pages/iniciativas/index.js
ya funciona el checked de Donaciones, Ahora falta el de categorías
> Renderizado Donaciones

- Components/Formempresas.jsx
> fixempresas

- package-lock.json
- pages/creariniciativas/index.js
se puede poner cbu/paypal/mercado pago cuando pones q es una iniciativa de donaciones en efectivo o si pones en especie
te deja agregar que items aceptas(Ej: Arroz, utiles, ropa, madera ,etc.) Falta mandarlo en el formdata2 al back cuando agreguen esas props a los modelos.
> formdonaciones

- Components/Formusers.jsx
se agrego q puedan poner imagen de perfil al crear un typeofuser user. Las ongs o empresas deberan editarlo en su perfil con el PUT. Falta q agreguen esa propiedad image en los modelos del back para poder mandarlo.
> imageperfilenformusers

- pages/review/index.js
se agrego q se pueda obtener el userid del localstorage en teoria, y lo q hay q mandar al post al back
> minifixesreview

- Components/Formusers.jsx
- pages/perfilusuario/index.js
ahora creando el user podes ponerte tu foto de perfil.
en perfil usuario podes modificarla y se actualiza el localstorage cuando lo haces
> fixesperfilusuario

- pages/perfilcompany/index.js
AGREGAR PUT DE COMPANY EN FUTURO
> AGREGAR PUT DE COMPANY EN FUTURO

- pages/creariniciativas/index.js
agregado rubro y quitado cbu y lista de items q aceptan
> creariniciativasfinal

- pages/review/index.js
> formreviewV99999

- pages/dashboard/iniciativas/IniciativasCards.jsx
> Bugsfinales
